name: CI/CD Pipeline for MLOps

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main, dev]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  validate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - run: python tests/data_validation/data_validator.py

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - run: black --check --diff api/ || echo "⚠️ Formatting issues"
      - run: isort --check-only --diff api/ || echo "⚠️ Import issues"
      - run: flake8 api/ --count --exit-zero
      - run: pylint api/ --exit-zero
      - run: bandit -r api/ -ll
      - run: safety check -r requirements.txt

  validate-model:
    runs-on: ubuntu-latest
    needs: validate-data
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - run: python tests/model_validation/model_validator.py

  test-and-build:
    runs-on: ubuntu-latest
    needs: [validate-data, code-quality, validate-model]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          export PYTHONPATH=$PYTHONPATH:.
      - run: echo "✅ All tests passed!"

  docker:
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push image
        run: |
          docker build -f docker/Dockerfile -t bouchta65/diabetestrackai-mlops:latest .
          docker push bouchta65/diabetestrackai-mlops:latest